---
- name: Deploy the cell
  shell: >
    set -o pipefail &&
    {{ working_dir }}/overcloud-deploy-cell.sh 2>&1 {{ timestamper_cmd }} > {{ deploy_cell_log }}
  register: deploy_cell_script_result
  ignore_errors: true
  when: step_deploy_cell|bool

- name: Export actual used deploy args for persistence to other plays
  set_fact:
    # deploy_args end with a newline, remove to make deploy_args_used easier to use
    deploy_args_used: "{{ deploy_args | replace('\n', ' ') }}"
    cacheable: true

- name: Export actual used cell deploy args for persistence to other plays
  set_fact:
    # cell_deploy_args end with a newline, remove to make cell_deploy_args_used easier to use
    cell_deploy_args_used: "{{ cell_deploy_args | replace('\n', ' ') }}"
    cacheable: true
