---
- include: pre-deploy.yml
  tags:
    - overcloud-scripts

- include: create-scripts.yml
  tags:
    - overcloud-scripts

- include: deployed-server.yml
  when: deployed_server|bool and not (deploy_steps_ansible_workflow|bool)
  tags:
    - overcloud-deploy

- include: deploy-overcloud.yml
  tags:
    - overcloud-deploy

- include: overcloud-status.yml
  tags:
    - overcloud-deploy

- include: post-deploy.yml
  tags:
    - overcloud-post-deploy
  when: overcloud_deploy_result is defined and overcloud_deploy_result == "passed"

- block:
    - include: pre-cell-deploy.yml
      tags:
        - overcloud-scripts-cell
    - include: deploy-cell.yml
      tags:
        - overcloud-deploy-cell
  when:
    - additional_cell|bool
    - overcloud_deploy_result is defined and overcloud_deploy_result == "passed"
